sudo: required
services:
  - docker

before_install:
  - docker build -t rashed091/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true rashed091/react-app npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-744380701768"
  bucket_path: "react-app"
  on:
    branch: master
